# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20160709_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
