# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_auto_20160709_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.PositiveIntegerField(primary_key='True', serialize=False),
        ),
    ]
