# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0005_auto_20160711_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
