# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_admin', '0007_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date_created')),
                ('unit', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date_required', models.DateTimeField(verbose_name='date_required')),
                ('date_arrived', models.DateTimeField(verbose_name='date_arrived')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=3)),
                ('supplier_is_unique', models.BooleanField()),
                ('date_authorized', models.DateTimeField(auto_now=True, verbose_name='date_authorized')),
                ('date_buyed', models.DateTimeField(auto_now=True, verbose_name='date_buyed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Project')),
                ('requested_items', models.ManyToManyField(through='project_admin.RequestItem', to='project_admin.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(through='project_admin.Cost', to='project_admin.Item')),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Supplier'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Requisition'),
        ),
        migrations.AddField(
            model_name='cost',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Item'),
        ),
        migrations.AddField(
            model_name='cost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.Supplier'),
        ),
    ]
